from typing import Any
from pydantic import BaseModel, Field
from src.agents.schemas.agent_extract_schemas import ExtractionStatus

class DocumentFields(BaseModel):
    is_required: bool = Field(
        default=False,
        description="Mark if field is required to have value or nullable"
    )
    field: str = Field(
        ...,
        description="Field to extract in the document. eg.: first_name",
    )
    
# ================
# MODELS FOR AGENT
# ================
# request model to pass for agent
class FieldsToExtractByAgent(BaseModel):
    document_name: str = Field(
        ...,
        description="e.g: National ID, Phil Health ID"
    )
    fields: list[DocumentFields] = Field(
        description="Target fields to extract by agent"
    )

# response model generated by agent
class FieldValuePair(BaseModel):
    field: str = Field(..., description="The name of the field, eg: first_name")
    value: str | None = Field(default=None, description="The extracted value of the field")

class ValuesExtractedByAgent(BaseModel): # response use by the agent
    field_values: list[FieldValuePair] = Field(
        description="Extracted field name and value pairs from the document."
    )
    confidence_score: float = Field( # generated by llm
        0.10,
        description="Agent provided confidence score from 1-100. Examples: 0.84, 0.92, 0.99",
    )
    score_reason: str = Field(
        None, 
        description="Provide 10 max words reason behind confidence score."
    )

# =======================
# FINAL METHOD RESPONSE
# =======================
class AgentExtractValuesResponse(BaseModel):
    document_id: str = Field( 
        default=None, 
        description="unique document_type identifier."
    )  
    file_id: str = Field( 
        default=None, 
        description="unique file name identifier."
    )
    document_name: str = Field(
        ...,
        description="e.g: National ID, Phil Health ID"
    )
    file_name: str = Field(
        ...,
        description="e.g: my_national_id.png"
    )
    field_values: dict[str, Any] = Field(
        description="Extracted field values as a key-value dictionary."
    )
    confidence_score: float = Field(
        0.10,
        description="Agent provided confidence score from 1-100. Examples: 0.84, 0.92, 0.99",
    )
    score_reason: str = Field(
        None, 
        description="Provide 10 max words reason behind confidence score."
    )
    status: ExtractionStatus = ExtractionStatus.SUCCESS
    error: str | None = None  # only populated on failure
